name: CodeGuru Review

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

  schedule:
  - cron: '*/60 * * * *'

jobs:
  cg_review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Region to access CodeGuru 

      - name: CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@v1.1
        with:
          s3_bucket: codeguru-reviewer-fses
        
      - name: Upload Result
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: codeguru-results.sarif.json

  pep_check:
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.5'

      - name: Install flake8
        run: pip install flake8

      - name: Debug
        run: |
          python --version
          pip freeze

      - name: Run flake8 check
        run: flake8 --exclude=venv,__pycache__,.github