name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: One line script
      run: echo Hello
    - name: Multi line
      run: |
        echo Line1
        echo Line2